{"error": {
  "code": 400,
  "context": "Test file ExDTest5.json",
  "details": [
    {
      "code": "JSONException",
      "message": "caught and rethrow from level: 3123123123",
      "param0": "3123123123",
      "template": "caught and rethrow from level: {0}"
    },
    {
      "code": "JSONException",
      "message": "caught and rethrow from level: 3123123",
      "param0": "3123123",
      "template": "caught and rethrow from level: {0}"
    },
    {
      "code": "JSONException",
      "message": "caught and rethrow from level: 3123",
      "param0": "3123",
      "template": "caught and rethrow from level: {0}"
    },
    {
      "code": "JSONException",
      "message": "caught and rethrow from level: 3",
      "param0": "3",
      "template": "caught and rethrow from level: {0}"
    },
    {
      "code": "Exception",
      "message": "top level exception thrown by exception test when course string ran out"
    }
  ],
  "innerError": {},
  "stack": [
    "top level exception thrown by exception test when course string ran out",
    "    TestExceptions.java: callHigher: 121",
    "    TestExceptions.java: sampleMethod3: 116",
    "    TestExceptions.java: callHigher: 131",
    "    TestExceptions.java: sampleMethod2: 83",
    "caught and rethrow from level: 3",
    "    TestExceptions.java: sampleMethod2: 111",
    "    TestExceptions.java: callHigher: 128",
    "    TestExceptions.java: sampleMethod1: 64",
    "    TestExceptions.java: callHigher: 125",
    "    TestExceptions.java: sampleMethod3: 116",
    "    TestExceptions.java: callHigher: 131",
    "    TestExceptions.java: sampleMethod2: 80",
    "caught and rethrow from level: 3123",
    "    TestExceptions.java: sampleMethod2: 111",
    "    TestExceptions.java: callHigher: 128",
    "    TestExceptions.java: sampleMethod1: 64",
    "    TestExceptions.java: callHigher: 125",
    "    TestExceptions.java: sampleMethod3: 116",
    "    TestExceptions.java: callHigher: 131",
    "    TestExceptions.java: sampleMethod2: 77",
    "caught and rethrow from level: 3123123",
    "    TestExceptions.java: sampleMethod2: 111",
    "    TestExceptions.java: callHigher: 128",
    "    TestExceptions.java: sampleMethod1: 64",
    "    TestExceptions.java: callHigher: 125",
    "    TestExceptions.java: sampleMethod3: 116",
    "    TestExceptions.java: callHigher: 131",
    "    TestExceptions.java: sampleMethod2: 74",
    "caught and rethrow from level: 3123123123",
    "    TestExceptions.java: sampleMethod2: 111",
    "    TestExceptions.java: callHigher: 128",
    "    TestExceptions.java: sampleMethod1: 64",
    "    TestExceptions.java: callHigher: 125",
    "    TestExceptions.java: testExceptionStackTrace: 178"
  ]
}}